# Generated by Django 5.0.3 on 2024-03-16 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('content', models.TextField(verbose_name='Контент')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='products.category', verbose_name='категория')),
                ('tags', models.ManyToManyField(blank=True, related_name='news', to='products.tag', verbose_name='теги')),
            ],
        ),
        migrations.CreateModel(
            name='NewsAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='название')),
                ('value', models.CharField(max_length=100, verbose_name='значение')),
                ('link', models.URLField(blank=True, null=True, verbose_name='ссылка')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.product', verbose_name='новость')),
            ],
            options={
                'verbose_name': 'атрибут новостя',
                'verbose_name_plural': 'атрибуты новостей',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images', verbose_name='Фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image', to='products.product')),
            ],
        ),
    ]
