# Generated by Django 5.0.3 on 2024-03-16 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='название')),
                ('value', models.CharField(max_length=100, verbose_name='значение')),
                ('link', models.URLField(blank=True, null=True, verbose_name='ссылка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'атрибут продукта',
                'verbose_name_plural': 'атрибуты ',
            },
        ),
        migrations.DeleteModel(
            name='NewsAttribute',
        ),
    ]
